/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(guppi_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1ca26412393a1c8bf3357f69f23f9e85)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/guppi/guppi_sink.h>
// pydoc.h is automatically generated in the build directory
#include <guppi_sink_pydoc.h>

void bind_guppi_sink(py::module& m)
{

    using guppi_sink    = ::gr::guppi::guppi_sink;


    py::class_<guppi_sink, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<guppi_sink>>(m, "guppi_sink", D(guppi_sink))

        .def(py::init(&guppi_sink::make),
           py::arg("filename"),
           py::arg("obsnchan"),
           py::arg("ndim"),
           py::arg("npol"),
           py::arg("obsfreq"),
           py::arg("obsbw"),
           py::arg("telescope"),
           py::arg("observer"),
           py::arg("src_name"),
           py::arg("proj_id"),
           py::arg("ra"),
           py::arg("dec"),
           py::arg("az"),
           py::arg("za"),
           py::arg("stt_mjd"),
           D(guppi_sink,make)
        )
        



        ;




}








