/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(guppi_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(94267759b2b40a5da8e2e0362c7a87f3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/guppi/guppi_sink.h>
// pydoc.h is automatically generated in the build directory
#include <guppi_sink_pydoc.h>

void bind_guppi_sink(py::module& m)
{

    using guppi_sink    = ::gr::guppi::guppi_sink;


    py::class_<guppi_sink, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<guppi_sink>>(m, "guppi_sink", D(guppi_sink))

        .def(py::init(&guppi_sink::make),
           py::arg("filename"),
           py::arg("obsnchan"),
           py::arg("ndim"),
           py::arg("num_polarizations"),
           py::arg("obsfreq"),
           py::arg("obsbw"),
           D(guppi_sink,make)
        )
        



        ;




}








