name: clang-format lint

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: gnuradio/clang-format-lint-action@v0.5-4
      with:
        source: '.'
        extensions: 'h,hpp,cpp,cc'
        exclude: './python/guppi/bindings'
